name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Xliff
        if: always()
        run: |
          sudo apt-get install libxml2-utils
          # shellcheck disable=2046
          xmllint --noout $(find . -iname '*.xlf' -o -iname '*.4DCatalog' -o -iname '*.4DSettings')
